apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: product-service-v1
  namespace: argocd
spec: 
  destination: 
    namespace: litethinking
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    #path: product-service-v1
    repoURL: "https://github.com/javierWill08/product-service-v1.git"
    targetRevision: trunk
  syncPolicy:
    syncOptions:
      - CreateNamespace=true